### ISSUE TITLE
Changing feeds

### ISSUE THREAD

**Issue by asmikhailov** [Zimbra-Community/annoucements#1]
Hello, it's great idea for announcements portal!
I did stuck with changing feed sources. I did change feed1url and feed2url in config_template.xml, but no success. It's still trying to fetch Zima Blog & Nexctcloud news. Can you give me advice to solve my problem?

**Comment by asmikhailov** [comment]
rtfm. stupid question, sorry.

**Comment by ghost** [comment]
@asmikhailov these are the best issue reports, opened and closed by user!
