### ISSUE TITLE
Announcements management

### ISSUE THREAD

**Issue by asmikhailov** [Zimbra-Community/annoucements#2]
Will you improve zimlet with management tools, such edit/remove announcements and permissions to read/write?

**Comment by ghost** [comment]
Yeah, it is the idea, but I am waiting for at least one customer to back me up on this.

**Comment by andreasmalta** [comment]
nice plugin, simple and easy! and I share the same feelings about additional features as above... ;-)

**Comment by ghost** [comment]
If anyone has a budget or considers a donation, I am more that willing to add those features. You can shoot your thoughts here or pm info@barrydegraaff.tk
