### ISSUE TITLE
Testing and changing config does not work

### ISSUE THREAD

**Issue by mailanetworks** [Zimbra-Community/annoucements#4]
Hi,

How can one change the config and apply?
Even after changing the configuration and restarting, it shows the old content.

Thanks,

**Comment by ghost** [comment]
If you deployed the zip file using `zmzimletctl deploy` or the automated installer you can configure the Zimlet using:

zmzimletctl getConfigTemplate /opt/zimbra/zimlets-deployed/tk_barrydegraaff_announcements > /tmp/config_template.xml.tmp

nano /tmp/config_template.xml.tmp

zmzimletctl configure /tmp/config_template.xml.tmp



In addition, if you want to change the database you can do it in 
/opt/zimbra/lib/ext/Announcements/db.properties

Restart mailbox for the changed to take effect:
zmmailboxdctl restart

and make sure to flush your browser cache/temporary files.

**Comment by mailanetworks** [comment]
Works as intended! Thank you!
