### ISSUE TITLE
Hide Left Sidebar?

### ISSUE THREAD

**Issue by sparadrus** [Zimbra-Community/annoucements#5]
Hi Barry,
Excuse me for this off-topic...
I use Portal (vanilla module from zimbra) and I want remove the left sidebar with mail tree...
Have you an idea how i can do that?
I've already full content in few Iframe Zimlet (new tab zimlet), but i don't know how does the same with Portal module....
Thanks,
Regards
Philippe

**Comment by ghost** [comment]
If you 

You can take a look at the Rocket Chat Zimlet where the sidebar on the left is removed. 

https://github.com/Zimbra-Community/zimbra-rocket/blob/master/zimlet/com_zimbra_rocket/com_zimbra_rocket.js#L86 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by sparadrus** [comment]
Hello Barry, many thanks !! I test that in few days.
I send an email for you at info@zetalliance.org for a project.
Best Regards,
Philippe

**Comment by sparadrus** [comment]
Hi, i'v try to adapt this code in Portal.js and Portal_All.js but i don't be able to remove sidebar.
Finally, i've just change my template :

#zv__PORTAL.ZmPortalView {
	width : 100% !important;
	left : 0px !important;
	background : #fff !important;
	z-index : 499 !important;
}
Isn't elegant but it's work
Voila ;)
Have you see my email on zetaalliance contact mailboxe? 
Have a nice day,
Philippe

**Comment by ghost** [comment]
yes I did reply to you couple of days ago. 

Kind regards, 

Barry de Graaff 
Zeta Alliance 
Co-founder & Developer 
zetalliance.org | github.com/Zimbra-Community 

Signal: +31 617 220 227 
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0
